//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("deneysan.Resources.Views.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Bilgileri.
        /// </summary>
        public static string bankaccounts {
            get {
                return ResourceManager.GetString("bankaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Değiştir.
        /// </summary>
        public static string changepass {
            get {
                return ResourceManager.GetString("changepass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        public static string contactdetails {
            get {
                return ResourceManager.GetString("contactdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Formu.
        /// </summary>
        public static string contactform {
            get {
                return ResourceManager.GetString("contactform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string culture {
            get {
                return ResourceManager.GetString("culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string culturename {
            get {
                return ResourceManager.GetString("culturename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dökümanlar.
        /// </summary>
        public static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string goback {
            get {
                return ResourceManager.GetString("goback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string homepage {
            get {
                return ResourceManager.GetString("homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        public static string institutional {
            get {
                return ResourceManager.GetString("institutional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantılar.
        /// </summary>
        public static string links {
            get {
                return ResourceManager.GetString("links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harita.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tum-haberler.
        /// </summary>
        public static string menu_allnews {
            get {
                return ResourceManager.GetString("menu_allnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basvuru.
        /// </summary>
        public static string menu_application {
            get {
                return ResourceManager.GetString("menu_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banka-hesaplari.
        /// </summary>
        public static string menu_bankaccounts {
            get {
                return ResourceManager.GetString("menu_bankaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kariyer.
        /// </summary>
        public static string menu_career {
            get {
                return ResourceManager.GetString("menu_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sifremidegistir.
        /// </summary>
        public static string menu_changepass {
            get {
                return ResourceManager.GetString("menu_changepass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletisim-bilgileri.
        /// </summary>
        public static string menu_contactdetails {
            get {
                return ResourceManager.GetString("menu_contactdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletisim-formu.
        /// </summary>
        public static string menu_contactform {
            get {
                return ResourceManager.GetString("menu_contactform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string menu_culture {
            get {
                return ResourceManager.GetString("menu_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dokumanlar.
        /// </summary>
        public static string menu_documents {
            get {
                return ResourceManager.GetString("menu_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anasayfa.
        /// </summary>
        public static string menu_homepage {
            get {
                return ResourceManager.GetString("menu_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hakkimizda.
        /// </summary>
        public static string menu_institutional {
            get {
                return ResourceManager.GetString("menu_institutional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linkler.
        /// </summary>
        public static string menu_links {
            get {
                return ResourceManager.GetString("menu_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/giris.
        /// </summary>
        public static string menu_login {
            get {
                return ResourceManager.GetString("menu_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yeniuyelik.
        /// </summary>
        public static string menu_newrecord {
            get {
                return ResourceManager.GetString("menu_newrecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haberler.
        /// </summary>
        public static string menu_news {
            get {
                return ResourceManager.GetString("menu_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teklif.
        /// </summary>
        public static string menu_offer {
            get {
                return ResourceManager.GetString("menu_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urunler.
        /// </summary>
        public static string menu_products {
            get {
                return ResourceManager.GetString("menu_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projebasvuru.
        /// </summary>
        public static string menu_projebasvuru {
            get {
                return ResourceManager.GetString("menu_projebasvuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projeler.
        /// </summary>
        public static string menu_project {
            get {
                return ResourceManager.GetString("menu_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projeler.
        /// </summary>
        public static string menu_projects {
            get {
                return ResourceManager.GetString("menu_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to referanslar.
        /// </summary>
        public static string menu_references {
            get {
                return ResourceManager.GetString("menu_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vizyon-misyon.
        /// </summary>
        public static string menu_visionmision {
            get {
                return ResourceManager.GetString("menu_visionmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projelistesi.
        /// </summary>
        public static string menuprojects_link {
            get {
                return ResourceManager.GetString("menuprojects_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamı ».
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Listem.
        /// </summary>
        public static string myofferlist {
            get {
                return ResourceManager.GetString("myofferlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Üyelik.
        /// </summary>
        public static string newrecord {
            get {
                return ResourceManager.GetString("newrecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENEYSAN - Eğitim Cihazları.
        /// </summary>
        public static string pagetitle {
            get {
                return ResourceManager.GetString("pagetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜNLER.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje adını giriniz....
        /// </summary>
        public static string projearamasearch {
            get {
                return ResourceManager.GetString("projearamasearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/projebasvuru.
        /// </summary>
        public static string projebasvurulinki {
            get {
                return ResourceManager.GetString("projebasvurulinki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Başvurusu.
        /// </summary>
        public static string projebasvurusu {
            get {
                return ResourceManager.GetString("projebasvurusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Proje Başvurusu.
        /// </summary>
        public static string projebasvurutext {
            get {
                return ResourceManager.GetString("projebasvurutext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Listesi.
        /// </summary>
        public static string projectlist_header {
            get {
                return ResourceManager.GetString("projectlist_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeler.
        /// </summary>
        public static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslar.
        /// </summary>
        public static string references {
            get {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen gerekli alanları eksiksiz ve doğru bir şekilde doldurunuz.
        /// </summary>
        public static string requiredfields {
            get {
                return ResourceManager.GetString("requiredfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site içi arama.
        /// </summary>
        public static string searchinsite {
            get {
                return ResourceManager.GetString("searchinsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Değiştir.
        /// </summary>
        public static string sifremidegis {
            get {
                return ResourceManager.GetString("sifremidegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi D..
        /// </summary>
        public static string taxoffice {
            get {
                return ResourceManager.GetString("taxoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyon&amp;Misyon.
        /// </summary>
        public static string visionmision {
            get {
                return ResourceManager.GetString("visionmision", resourceCulture);
            }
        }
    }
}
